# -*- coding: utf-8 -*-
"""Troisième série : 30 reels EXPLIQUÉS par la voix malgache Abidi, à 10:00 (20/09 → 19/10/2026).

Demande d'Andry (18/09/2026, 22 h 50) : « crée des reels, et travaille avec les voix
malgaches comme Abidi, pour explication » puis « fais pour 30 j, regarde les bonnes heures
pour les publications ».

Heure : 10:00, mesurée et non devinée. 797 messages clients depuis 2025 : pics à 10 h, 13 h,
15 h et 18 h ; les publications de 10 h ont eu 0,96 réaction en moyenne (170 publications),
18 h 0,81, 7 h 0,5. 14:00 et 18:00 sont déjà pris par les deux autres séries.

Règles de la voix (skill fonenako-tuto-video) :
- alphabet malgache seulement (pas de c, u, q, w, x, ç) — sauf « hourdis », dit selon le
  lexique choisi à l'oreille par Andry (voix_reels.py : PRONONCIATION) ;
- les nombres s'écrivent {n:3400} : voix_reels.py les dit en toutes lettres (même forme que
  la narration validée du 28/09 : « iray hetsy sy roa alina ») et la légende les écrit en
  chiffres — le montant dit ne peut pas diverger du montant affiché ;
- question fermée = particule « ve ».
Chaque scène couvre des phrases de « voix » (indices) : l'image change quand la phrase change.
"""
from serie import CIBLES  # noqa: F401

HEURE = "10:00"
CAMPAGNE = "reels-voix"
PREFIXE = "v"
SORTIE_NOM = "sortie-voix"
NOM = "-voix"
DEBUT = "2026-09-20"

SERIE = [
    {"slug": "inona-ny-hourdis", "photo": "p01", "cible": "accueil", "titre": "Inona marina ny hourdis ?",
     "voix": ["Inona marina ny hourdis ?",
              "Biriky misy lavaka izy, vita amin'ny tanimanga voadoro.",
              "Apetraka eo anelanelan'ireo andry betôna izy, rehefa manao gorodona rihana.",
              "Manolo ny hazo be dia be izy, ary manamaivana ny gorodona.",
              "Eto Ambohimanga Rova no anaovanay azy."],
     "scenes": [{"phrases": [0], "badge": "HAZAVAINA", "titre": "Inona ny hourdis ?"},
                {"phrases": [1, 2], "titre": "Biriky misy lavaka", "sous": "eo anelanelan'ny poutrelle"},
                {"phrases": [3, 4], "lignes": ["Tsy mila hazo be dia be", "Maivana kokoa ny gorodona"]}]},
    {"slug": "ahoana-no-anaovana", "photo": "p36", "cible": "production", "titre": "Ahoana no anaovana ny hourdis ?",
     "voix": ["Ahoana no anaovanay ny hourdis ?",
              "Voalohany, ny tanimanga, avy eto an-toerana.",
              "Faharoa, ny milina no manome azy ny endriny sy ny lavaka.",
              "Fahatelo, avela ho maina moramora mandritra ny andro maro.",
              "Farany, dorana ao anaty lafaoro mandra-pahamafiny.",
              "Izany no antony anaovanay azy rehefa misy fanafarana."],
     "scenes": [{"phrases": [0], "badge": "ATELIER", "titre": "Ahoana no anaovana azy ?"},
                {"phrases": [1, 2], "lignes": ["1 · Tanimanga", "2 · Famolavolana"]},
                {"phrases": [3, 4, 5], "lignes": ["3 · Fanamainana", "4 · Fandorana"]}]},
    {"slug": "sivy-isaky-ny-m2", "photo": "p10", "cible": "produits", "titre": "Firy ny hourdis ilainao ?",
     "voix": ["Firy ny hourdis ilainao ?",
              "Kajy iray monja : sivy isaky ny metatra toradroa.",
              "Ohatra, gorodona {n:40} metatra toradroa : {n:360} hourdis.",
              "Ampio kely ho an'ny vaky, telo ka hatramin'ny dimy isan-jato.",
              "Ao amin'ny tranonkalanay, ny kajy no manao izany ho anao."],
     "scenes": [{"phrases": [0], "badge": "KAJY", "titre": "Firy ny hourdis ilainao ?"},
                {"phrases": [1, 2], "titre": "9 isaky ny m²", "lignes": ["40 m² → 360 pièces"]},
                {"phrases": [3, 4], "titre": "+ 3 à 5 %", "sous": "ho an'ny vaky"}]},
    {"slug": "hourdis-12-15-20", "photo": "p06", "cible": "produits", "titre": "Hourdis 12, 15 sa 20 ?",
     "voix": ["Hourdis {n:12}, {n:15}, sa {n:20} ?",
              "Samy {n:33} santimetatra ny halavany sy ny sakany.",
              "Ny haavony ihany no tsy mitovy.",
              "Arakaraka ny elanelana eo amin'ny tohana roa sy ny entana no isafidianana azy.",
              "Ny injeniera na ny lehiben'ny toeram-panorenana no mifidy, araka ny drafitrao."],
     "scenes": [{"phrases": [0], "badge": "HOURDIS", "titre": "12, 15 sa 20 ?"},
                {"phrases": [1, 2], "titre": "33 × 33 cm daholo", "sous": "ny haavony ihany no miova"},
                {"phrases": [3, 4], "lignes": ["12 · portée kely", "15 · trano fonenana", "20 · portée lava"]}]},
    {"slug": "tsy-mila-hazo", "photo": "p02", "cible": "faq", "titre": "Nahoana no mora kokoa ny gorodona hourdis ?",
     "voix": ["Nahoana no mora kokoa ny gorodona hourdis ?",
              "Ny gorodona betôna feno dia mila hazo be dia be eo ambany.",
              "Ny hourdis kosa no misolo io hazo io.",
              "Betôna vitsy kokoa no arotsaka : efatra ka hatramin'ny dimy santimetatra eo ambony.",
              "Maivana kokoa ny gorodona, ary mora kokoa ny fanaovana azy."],
     "scenes": [{"phrases": [0], "badge": "FAMPITAHANA", "titre": "Nahoana no mora kokoa ?"},
                {"phrases": [1], "titre": "Dalle pleine", "lignes": ["Hazo be dia be", "Betôna be"]},
                {"phrases": [2, 3, 4], "titre": "Hourdis", "lignes": ["Tsy mila hazo be", "Betôna 4 à 5 cm", "Maivana kokoa"]}]},
    {"slug": "fametrahana-1", "photo": "p09", "cible": "faq", "titre": "Fametrahana gorodona hourdis 1/3",
     "voix": ["Fametrahana gorodona hourdis, dingana voalohany.",
              "Apetraka eo ambonin'ny rindrina mitondra entana ireo andry betôna.",
              "Telopolo sy telo santimetatra eo ho eo ny elanelan'izy ireo, araka ny drafitra.",
              "Asiana tohana tsara izy ireo, alohan'ny hanaovana zavatra hafa."],
     "scenes": [{"phrases": [0], "badge": "FAMETRAHANA 1/3", "titre": "Ireo andry betôna"},
                {"phrases": [1, 2], "lignes": ["Eo ambonin'ny rindrina mitondra entana", "Elanelana ≈ 33 cm"]},
                {"phrases": [3], "lignes": ["Tohana tsara aloha"]}]},
    {"slug": "fametrahana-2", "photo": "p08", "cible": "faq", "titre": "Fametrahana gorodona hourdis 2/3",
     "voix": ["Dingana faharoa : ny hourdis.",
              "Ampidirina amin'ny tanana eo anelanelan'ny andry roa izy.",
              "Tsy mila hazo firafitra, fa ny hourdis mihitsy no misolo azy.",
              "Aza mandeha mivantana eo ambonin'ny hourdis : mandehana amin'ny hazo fisaka."],
     "scenes": [{"phrases": [0], "badge": "FAMETRAHANA 2/3", "titre": "Ny hourdis"},
                {"phrases": [1, 2], "lignes": ["Apetraho amin'ny tanana", "Tsy mila hazo"]},
                {"phrases": [3], "lignes": ["Aza mandeha eo ambony", "Mandehana amin'ny hazo fisaka"]}]},
    {"slug": "fametrahana-3", "photo": "p05", "cible": "faq", "titre": "Fametrahana gorodona hourdis 3/3",
     "voix": ["Dingana fahatelo : ny betôna.",
              "Apetraho eo ambony ny harato vy.",
              "Arotsaho ny betôna, efatra ka hatramin'ny dimy santimetatra ny hateviny.",
              "Avelao eo ny tohana mandra-pahamafin'ny betôna : telo ka hatramin'ny efatra herinandro."],
     "scenes": [{"phrases": [0], "badge": "FAMETRAHANA 3/3", "titre": "Ny betôna"},
                {"phrases": [1, 2], "lignes": ["Harato vy eo ambony", "Betôna 4 à 5 cm"]},
                {"phrases": [3], "titre": "21 à 28 andro", "sous": "vao esorina ny tohana"}]},
    {"slug": "aza-mandeha-eo-ambony", "photo": "p07", "cible": "faq", "titre": "Aza mandeha eo ambonin'ny hourdis",
     "voix": ["Fahadisoana iray matetika hita : mandeha eo ambonin'ny hourdis.",
              "Alohan'ny handatsahana betôna, tsy natao hitondra lanja olona ny hourdis irery.",
              "Mety ho vaky izy, ary very maimaim-poana ny volanao.",
              "Mandehana foana amin'ny hazo fisaka apetraka eo ambonin'ny andry."],
     "scenes": [{"phrases": [0], "badge": "FAHADISOANA", "titre": "Aza mandeha eo ambony"},
                {"phrases": [1, 2], "lignes": ["Mety ho vaky", "Very ny volanao"]},
                {"phrases": [3], "lignes": ["Hazo fisaka eo ambonin'ny andry"]}]},
    {"slug": "tohana-aloha-loatra", "photo": "p04", "cible": "faq", "titre": "Aza esorina aloha loatra ny tohana",
     "voix": ["Fahadisoana faharoa : manala ny tohana aloha loatra.",
              "Mila fotoana ny betôna vao mafy tsara.",
              "Avelao eo ny tohana, telo ka hatramin'ny efatra herinandro.",
              "Aza maika : ny faharetan'ny tranonao no miankina amin'izany."],
     "scenes": [{"phrases": [0], "badge": "FAHADISOANA", "titre": "Tohana esorina aloha loatra"},
                {"phrases": [1, 2], "titre": "21 à 28 andro", "sous": "vao esorina ny tohana"},
                {"phrases": [3], "titre": "Aza maika"}]},
    {"slug": "tahiry-ho-an-ny-vaky", "photo": "p03", "cible": "produits", "titre": "Ampio kely ho an'ny vaky",
     "voix": ["Firy ny hourdis tokony ho vidinao ?",
              "Ampio telo ka hatramin'ny dimy isan-jato amin'ny isa marina.",
              "Misy vaky foana rehefa mitondra sy mametraka, ary misy tapahina amin'ny sisiny.",
              "Tsara kokoa ny misy ambiny kely, toy izay mijanona ny asa."],
     "scenes": [{"phrases": [0], "badge": "TORO-HEVITRA", "titre": "Firy no ho vidinao ?"},
                {"phrases": [1], "titre": "+ 3 à 5 %", "sous": "amin'ny isa marina"},
                {"phrases": [2, 3], "lignes": ["Vaky amin'ny fitaterana", "Tapahina amin'ny sisiny", "Tsy mijanona ny asa"]}]},
    {"slug": "fitehirizana", "photo": "p33", "cible": "faq", "titre": "Ahoana no hitehirizana ny hourdis ?",
     "voix": ["Tonga eo amin'ny toeram-panorenana ny hourdis : ahoana no hitehirizana azy ?",
              "Aza apetraka mivantana amin'ny tany lena : asio hazo eo ambany.",
              "Apetraho lavitra ny lalana fandehanan'ny fiara.",
              "Ary ampidino moramora, fa aza atsipy."],
     "scenes": [{"phrases": [0], "badge": "TORO-HEVITRA", "titre": "Eo amin'ny toeram-panorenana"},
                {"phrases": [1], "lignes": ["Hazo eo ambany", "Tsy amin'ny tany lena"]},
                {"phrases": [2, 3], "lignes": ["Lavitry ny fiara", "Aza atsipy"]}]},
    {"slug": "tariby-sy-fantsona", "photo": "p37", "cible": "faq", "titre": "Aiza no andehanan'ny tariby ?",
     "voix": ["Aiza no andehanan'ny tariby herinaratra ao amin'ny gorodona hourdis ?",
              "Ao anaty lavaky ny hourdis mihitsy !",
              "Mandalo ao ny tariby sy ny fantsona, tsy mila mandavaka betôna.",
              "Ataovy fotsiny ny lalana handehanany, alohan'ny handatsahana betôna."],
     "scenes": [{"phrases": [0], "badge": "HAZAVAINA", "titre": "Aiza no andehanan'ny tariby ?"},
                {"phrases": [1, 2], "lignes": ["Ao anaty lavaka", "Tariby sy fantsona"]},
                {"phrases": [3], "lignes": ["Ataovy alohan'ny betôna"]}]},
    {"slug": "biriky-misy-lavaka", "photo": "p14", "cible": "produits", "titre": "Biriky misy lavaka : 12 isaky ny m²",
     "voix": ["Ny biriky misy lavaka : {n:12} isaky ny metatra toradroa amin'ny rindrina.",
              "Maivana kokoa noho ny biriky feno izy.",
              "Ny rivotra voahidy ao anaty lavaka no miaro amin'ny hafanana sy ny tabataba.",
              "Ohatra, rindrina {n:30} metatra toradroa : {n:360} biriky."],
     "scenes": [{"phrases": [0], "badge": "BRIQUE CREUSE", "titre": "12 isaky ny m²"},
                {"phrases": [1, 2], "lignes": ["Maivana kokoa", "Miaro amin'ny hafanana"]},
                {"phrases": [3], "titre": "30 m² → 360 pièces"}]},
    {"slug": "biriky-10-15-20", "photo": "p18", "cible": "produits", "titre": "Biriky 10, 15 sa 20 ?",
     "voix": ["Biriky misy lavaka {n:10}, {n:15}, sa {n:20} : iza no ho an'ny rindrina inona ?",
              "Folo santimetatra : rindrina fisarahana ao anatin'ny trano.",
              "Dimy ambin'ny folo : rindrina ivelany sy tava trano.",
              "Roapolo : rindrina mitondra entana.",
              "Ny injeniera no mamaritra, araka ny drafitrao."],
     "scenes": [{"phrases": [0], "badge": "BRIQUE CREUSE", "titre": "10, 15 sa 20 ?"},
                {"phrases": [1, 2, 3], "lignes": ["10 cm · cloison · 2 500 Ar", "15 cm · façade · 3 000 Ar",
                                                   "20 cm · mitondra entana · 3 500 Ar"]},
                {"phrases": [4], "titre": "Ny injeniera no mamaritra"}]},
    {"slug": "kajy-rindrina", "photo": "p15", "cible": "produits", "titre": "Firy ny biriky ho an'ny rindrinao ?",
     "voix": ["Firy ny biriky ho an'ny rindrinao ?",
              "Ampitomboy ny halavany sy ny haavony.",
              "Ohatra, folo metatra ny halavany, roa metatra sy valopolo santimetatra ny haavony : {n:28} metatra toradroa.",
              "Esory ny varavarana sy ny varavarankely.",
              "Avy eo, ampitomboy roa ambin'ny folo : izay no isan'ny biriky."],
     "scenes": [{"phrases": [0], "badge": "KAJY", "titre": "Firy ny biriky ?"},
                {"phrases": [1, 2], "titre": "10 m × 2,8 m", "sous": "= 28 m²"},
                {"phrases": [3, 4], "titre": "m² × 12", "sous": "esory ny varavarana"}]},
    {"slug": "tanimanga-voadoro", "photo": "p20", "cible": "faq", "titre": "Nahoana ny tanimanga voadoro ?",
     "voix": ["Nahoana no tanimanga voadoro no safidianay ?",
              "Tsy may izy, satria efa nandalo afo.",
              "Miaro amin'ny tabataba sy ny hafanana izy.",
              "Ary tsy miova amin'ny fotoana : maharitra taona maro."],
     "scenes": [{"phrases": [0], "badge": "TERRE CUITE", "titre": "Nahoana ny tanimanga voadoro ?"},
                {"phrases": [1, 2], "lignes": ["Tsy may", "Miaro amin'ny tabataba", "Miaro amin'ny hafanana"]},
                {"phrases": [3], "titre": "Maharitra taona maro"}]},
    {"slug": "fanamainana", "photo": "p16", "cible": "production", "titre": "Fanamainana : tsy azo hafainganina",
     "voix": ["Fanamainana : dingana tsy azo hafainganina.",
              "Rehefa vao voaforona ny hourdis sy ny biriky, mbola lena izy ireo.",
              "Raha maina haingana loatra, mitriatra.",
              "Raha dorana nefa mbola lena, vaky ao anaty lafaoro.",
              "Ny fotoana no manome ny hamafiny."],
     "scenes": [{"phrases": [0], "badge": "ATELIER", "titre": "Fanamainana"},
                {"phrases": [1, 2, 3], "lignes": ["Maina haingana loatra : mitriatra", "Mbola lena : vaky"]},
                {"phrases": [4], "titre": "Ny fotoana no manome ny hamafiny"}]},
    {"slug": "fandorana", "photo": "p34", "cible": "production", "titre": "Fandorana : dingana farany",
     "voix": ["Fandorana : dingana farany amin'ny famokarana.",
              "Ao anaty lafaoro no ahazoan'ny tanimanga ny hamafiny.",
              "Ny fandorana ampy no manome loko mitovy sy faharetana.",
              "Izany no mahatonga ny hourdis tsara hanana feo madio rehefa dondonina."],
     "scenes": [{"phrases": [0], "badge": "ATELIER", "titre": "Fandorana"},
                {"phrases": [1, 2], "lignes": ["Hamafisana", "Loko mitovy", "Faharetana"]},
                {"phrases": [3], "titre": "Feo madio rehefa dondonina"}]},
    {"slug": "tafo-tanimanga", "photo": "p23", "cible": "produits", "titre": "Tuile mécanique : 2 200 Ar",
     "voix": ["Tafo tanimanga : {n:2200} ariary ny iray.",
              "Dimy ambin'ny folo isaky ny metatra toradroa amin'ny tafo.",
              "Tsy mafana toy ny tafo vy, rehefa mahamay ny masoandro.",
              "Ary tsy mitabataba, rehefa avy ny orana."],
     "scenes": [{"phrases": [0], "badge": "TUILE", "titre": "Tuile mécanique", "prix": "2 200 Ar"},
                {"phrases": [1], "titre": "15 isaky ny m²"},
                {"phrases": [2, 3], "lignes": ["Tsy mafana", "Tsy mitabataba rehefa avy ny orana"]}]},
    {"slug": "tafo-nentim-paharazana", "photo": "p26", "cible": "produits", "titre": "Tuile écaille : 500 Ar",
     "voix": ["Ny tafo tanimanga nentim-paharazana : {n:500} ariary ny iray.",
              "Kely izy, boribory ny tendrony, ary apetraka mifanindry.",
              "Fitopolo sy dimy isaky ny metatra toradroa.",
              "Tafo malagasy tena izy, maharitra taona maro."],
     "scenes": [{"phrases": [0], "badge": "TUILE ÉCAILLE", "titre": "Tafo nentim-paharazana", "prix": "500 Ar"},
                {"phrases": [1], "lignes": ["Kely, boribory tendrony", "Apetraka mifanindry"]},
                {"phrases": [2, 3], "titre": "75 isaky ny m²", "sous": "maharitra taona maro"}]},
    {"slug": "misy-foana-ve", "photo": "p17", "cible": "livraison", "titre": "Misy foana ve ny hourdis ?",
     "voix": ["Misy foana ve ny hourdis ?",
              "Amin'ny fanafarana no anaovanay azy : telopolo andro eo ho eo.",
              "Ny entana vita dia efa voatokana matetika ho an'izay nanafatra talohanao.",
              "Koa manafara aloha, dimy herinandro eo ho eo mialoha ny andro ilanao azy."],
     "scenes": [{"phrases": [0], "badge": "FANAFARANA", "titre": "Misy foana ve ?"},
                {"phrases": [1, 2], "titre": "≈ 30 andro", "sous": "amin'ny fanafarana"},
                {"phrases": [3], "lignes": ["Manafara aloha", "5 herinandro mialoha"]}]},
    {"slug": "fanaterana", "photo": "p27", "cible": "livraison", "titre": "Manatitra ve izahay ?",
     "voix": ["Manatitra hatrany amin'ny toeram-panorenanao ve izahay ? Eny.",
              "Any Antananarivo sy ny manodidina : Ambohimanga, Alasora, Imerintsiatosika, Andramasina.",
              "{n:1500} ariary isaky ny kilometatra, manomboka eto Ambohimanga Rova.",
              "Telo ka hatramin'ny fito andro aorian'ny fanamafisana."],
     "scenes": [{"phrases": [0], "badge": "FANATERANA", "titre": "Manatitra ve ?"},
                {"phrases": [1], "lignes": ["Antananarivo", "Ambohimanga · Alasora", "Imerintsiatosika · Andramasina"]},
                {"phrases": [2, 3], "titre": "1 500 Ar / km", "sous": "3 à 7 andro"}]},
    {"slug": "tombam-bidy", "photo": "p19", "cible": "devis", "titre": "Tombam-bidy maimaim-poana",
     "voix": ["Te hahafantatra ny vidiny marina ve ianao ?",
              "Lazao anay ny vokatra, ny isany na ny velarana, ary ny toerana hanaterana.",
              "Omenay anao maimaim-poana ny tombam-bidy : vidiny, fanaterana ary daty.",
              "Ho an'ny fanafarana lehibe, miresaha aminay."],
     "scenes": [{"phrases": [0], "badge": "TOMBAM-BIDY", "titre": "Maimaim-poana"},
                {"phrases": [1], "lignes": ["Vokatra", "Isany na velarana", "Toerana"]},
                {"phrases": [2, 3], "lignes": ["Vidiny · fanaterana · daty"]}]},
    {"slug": "kajy-ao-amin-ny-tranonkala", "photo": None, "capture": "calcul", "cible": "produits",
     "titre": "Kajio ny budget-nao ao amin'ny site",
     "voix": ["Te hikajy haingana ve ianao ?",
              "Ao amin'ny tranonkalanay, safidio ny vokatra tianao.",
              "Soraty ny velarana.",
              "Omeny anao avy hatrany ny isany sy ny vidiny, ary azonao alefa ho tombam-bidy."],
     "scenes": [{"phrases": [0], "badge": "TRANONKALA", "titre": "Kajio ny budget-nao"},
                {"phrases": [1, 2], "lignes": ["1 · Safidio ny vokatra", "2 · Soraty ny velarana"]},
                {"phrases": [3], "lignes": ["Isany sy vidiny avy hatrany"]}]},
    {"slug": "hourdis-tsara-kalitao", "photo": "p13", "cible": "faq", "titre": "Ahoana no hamantarana hourdis tsara ?",
     "voix": ["Ahoana no hamantarana hourdis tsara ?",
              "Dondony moramora : feo madio no henonao.",
              "Jereo ny sisiny : tsy misy triatra, tsy misy tapaka.",
              "Jereo ny loko : mitovy manontolo.",
              "Ary refeso : telopolo sy telo santimetatra tsara."],
     "scenes": [{"phrases": [0], "badge": "TORO-HEVITRA", "titre": "Hourdis tsara"},
                {"phrases": [1, 2], "lignes": ["Feo madio", "Tsy misy triatra"]},
                {"phrases": [3, 4], "lignes": ["Loko mitovy", "33 × 33 cm"]}]},
    {"slug": "budget-gorodona-80m2", "photo": "p22", "cible": "produits", "titre": "Gorodona 10 m × 8 m : ohatrinona ?",
     "voix": ["Gorodona folo metatra sy valo metatra : ohatrinona ny hourdis ?",
              "Valopolo metatra toradroa izany, ka {n:720} hourdis.",
              "Amin'ny hourdis dimy ambin'ny folo, {n:3000} ariary ny iray : {n:2160000} ariary.",
              "Tsy tafiditra ao ny fanaterana, ary ny tombam-bidy an-tsoratra no manan-kery."],
     "scenes": [{"phrases": [0], "badge": "BUDGET", "titre": "Gorodona 10 m × 8 m"},
                {"phrases": [1], "titre": "80 m² → 720 pièces"},
                {"phrases": [2, 3], "titre": "720 × 3 000 Ar", "sous": "= 2 160 000 Ar"}]},
    {"slug": "tsy-hourdis-ihany", "photo": "p28", "cible": "devis", "titre": "Tsy hourdis ihany",
     "voix": ["Tsy hourdis ihany no ataonay.",
              "Manao biriky fanaingoana rindrina koa izahay, manomboka amin'ny {n:500} ariary.",
              "Tsara ho an'ny rindrina tsy mila fandrakofana.",
              "Mila sary ve ianao ? Andefaso hafatra izahay."],
     "scenes": [{"phrases": [0], "badge": "VOKATRA HAFA", "titre": "Tsy hourdis ihany"},
                {"phrases": [1, 2], "titre": "Plaquette · briquette", "sous": "manomboka 500 Ar"},
                {"phrases": [3], "titre": "Mila sary ve ?"}]},
    {"slug": "aiza-no-misy-anay", "photo": "p24", "cible": "accueil", "titre": "Aiza no misy anay ?",
     "voix": ["Aiza no misy anay ?",
              "Eto Ambohimanga Rova, amin'ny lalana mandalo an'i Sabotsy Namehana.",
              "Eto no anaovanay sy itahirizanay ny hourdis, ny biriky, ary ny tafo tanimanga.",
              "Te hijery maso ve ianao ? Tongava, fa miantsoa aloha."],
     "scenes": [{"phrases": [0], "badge": "AMBOHIMANGA ROVA", "titre": "Aiza no misy anay ?"},
                {"phrases": [1, 2], "titre": "Ambohimanga Rova", "sous": "lalana mandalo an'i Sabotsy Namehana"},
                {"phrases": [3], "titre": "Tongava hijery", "sous": "fa miantsoa aloha : 032 47 041 43"}]},
    {"slug": "misaotra-anareo", "photo": "p25", "cible": "accueil", "titre": "Misaotra anareo !",
     "voix": ["Misaotra anareo nanaraka anay nandritra ity volana ity !",
              "Hourdis, biriky misy lavaka, tafo tanimanga : vita eto Madagasikara, eto Ambohimanga Rova.",
              "Manana tetikasa trano ve ianao ?",
              "Ao amin'ny tranonkalanay ny vidiny rehetra sy ny kajy."],
     "scenes": [{"phrases": [0], "badge": "HOURDIS MADAGASCAR", "titre": "Misaotra anareo !"},
                {"phrases": [1], "titre": "Vita eto Madagasikara"},
                {"phrases": [2, 3], "titre": "Manana tetikasa ve ?", "sous": "hourdis.fonenako.mg"}]},
]

# dates : une par jour à partir de DEBUT
from datetime import date as _d, timedelta as _td  # noqa: E402
for _i, _p in enumerate(SERIE):
    _p["date"] = (_d.fromisoformat(DEBUT) + _td(days=_i)).isoformat()
